[project]
name = "appsec-lab4"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "jinja2>=3.1.6",
    "python-dotenv>=1.1.1",
]
